{  
  scopeName = 'source.rascalmpl';
  patterns = (
    { 
      name = 'keyword.control.untitled';
      match = '\b(if|while|for|return|try|catch|visit|fail|switch|case|insert|append|syntax|lexical|keyword|data|alias)\b';
    },
    {  
      name = 'string.quoted.double.untitled';
      begin = '"';
      end = '"';
      patterns = ( 
        {
          name = 'constant.character.escape.untitled';
          match = '\\.';
        }
      );
    },
  );
}