<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>rsc</string>
	</array>
	<key>name</key>
	<string>Rascal</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#top_level</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>annotation</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(@[^ {]+)({)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.annotation.block.rascal</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.annotation-argument.begin.rascal</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(})</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.annotation-argument.end.rascal</string>
						</dict>
					</dict>
					<key>name</key>
					<string>comment.block.annotation.rascal</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.annotation.inline.rascal</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(@[A-Za-z_0-9]+)</string>
					<key>name</key>
					<string>meta.annotation.inline.rascal</string>
				</dict>
			</array>
		</dict>
		<key>char_set</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\[</string>
					<key>end</key>
					<string>\]</string>
					<key>name</key>
					<string>punctuation.other.lexicalcharset.rascal</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string_escape</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>comment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>//.*$\n?</string>
					<key>name</key>
					<string>comment.line.double-slash.rascal</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment.block.rascal</string>
				</dict>
			</array>
		</dict>
		<key>regex</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>/(?!/|*)</string>
					<key>end</key>
					<string>/([dims]*)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.regex.rascal</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.regexp.rascal</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#regex_escape</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#string_interpolation</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>regex_escape</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\(/|&lt;|&gt;|\\)</string>
					<key>name</key>
					<string>constant.character.escape.regex.rascal</string>
				</dict>
			</array>
		</dict>
		<key>string</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>end</key>
					<string>'</string>
					<key>name</key>
					<string>string.quoted.single.rascal</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string_escape</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>end</key>
					<string>"</string>
					<key>name</key>
					<string>string.quoted.double.rascal</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string_escape</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#string_interpolation</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>`</string>
					<key>end</key>
					<string>`</string>
					<key>name</key>
					<string>string.interpolated.rascal</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string_interpolation</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#syntax_escape</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>string_escape</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\(\"|\'|&lt;|&gt;|\\|[bnfrt])</string>
					<key>name</key>
					<string>constant.character.escape.ordinary.rascal</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\(u[0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f] |U(0[0-9 A-F a-f]|10)[0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f] |a[0-7][0-9A-Fa-f] )</string>
					<key>name</key>
					<string>constant.character.escape.unicode.rascal</string>
				</dict>
			</array>
		</dict>
		<key>string_interpolation</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(&lt;)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.interpolation.begin.rascal</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(&gt;)</string>
					<key>endCaptures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.interpolation.end.rascal</string>
						</dict>
					</dict>
					<key>name</key>
					<string>support.interpolated-string.rascal</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#top_level</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>syntax_escape</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\(\\|&lt;|&gt;|`)</string>
					<key>name</key>
					<string>constant.character.escape.syntax.rascal</string>
				</dict>
			</array>
		</dict>
		<key>top_level</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(lexical|syntax)\s+([a-zA-Z][A-Za-z_0-9]*)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.rascal</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.rascal</string>
						</dict>
					</dict>
					<key>end</key>
					<string>;</string>
					<key>name</key>
					<string>punctuation.other.syntactic.rascal</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#char_set</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#string</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comment</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#regex</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#annotation</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;![A-Za-z_])(0(?![0-9a-z_A-Z])|[1-9][0-9]*(?![0-9a-z_A-Z]))</string>
					<key>name</key>
					<string>constant.numeric.decimal.rascal</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;![A-Za-z_])0[Xx][0-9A-Fa-f]+(?![0-9a-z_A-Z])</string>
					<key>name</key>
					<string>constant.numeric.hex.rascal</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;![A-Za-z_])0[0-7]+(?![0-9a-z_A-Z])</string>
					<key>name</key>
					<string>constant.numeric.octal.rascal</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\\$</string>
					<key>end</key>
					<string>\\$</string>
					<key>name</key>
					<string>string.other.datetime.rascal</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;![A-Za-z_]) ([0-9]+[dDfF] |[0-9]+[eE][+\-]?[0-9]+[dDfF]? |[0-9]+\.(?!\.)[0-9]*[dDfF]? |[0-9]+\.[0-9]*[eE][+\-]?[0-9]+[dDfF]? |\.(?!\.)[0-9]+[dDfF]? |\.(?!\.)[0-9]+[eE][+\-]?[0-9]+[dDfF]? )</string>
					<key>name</key>
					<string>constant.numeric.real.rascal</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(true|false)\b</string>
					<key>name</key>
					<string>constant.language.bool.rascal</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;![A-Za-z_])([0-9][0-9]*r|[1-9][0-9]*r[0-9][0-9]*(?![0-9a-z_A-Z]))</string>
					<key>name</key>
					<string>constant.numeric.rational.rascal</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(syntax|keyword|lexical|break|continue|finally|private|fail|filter|if|tag|extend|append|non-assoc|assoc|test|anno|layout|data|join|it|bracket|in|import|all|solve|try|catch|notin|else|insert|switch|return|case|while|throws|visit|for|assert|default|map|alias|any|module|mod|public|one|throw|start)\b</string>
					<key>name</key>
					<string>keyword.control.rascal</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(value|loc|node|num|type|bag|int|rat|rel|lrel|real|tuple|str|bool|void|datetime|set|map|list)\b</string>
					<key>name</key>
					<string>support.type.basic.rascal</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#regex</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#annotation</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b[a-zA-Z][A-Za-z_0-9]*\b</string>
					<key>name</key>
					<string>variable.other.ordinary.rascal</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\(syntax|keyword|lexical|break|continue|finally|private|fail|filter|if|tag|extend|append|non-assoc|assoc|test|anno|layout|data|join|it|bracket|in|import|all|solve|try|catch|notin|else|insert|switch|return|case|while|throws|visit|for|assert|default|map|alias|any|module|mod|public|one|throw|start|value|loc|node|num|type|bag|int|rat|rel|lrel|real|tuple|str|bool|void|datetime|set|map|list)</string>
					<key>name</key>
					<string>variable.other.escaped-keyword.rascal</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>markup.underline.link.rascal</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\|([0-9a-z_A-Z.\-_~:/?#\[\]@!$&amp;'()*+,;=`])+\|</string>
					<key>name</key>
					<string>string.other.url.rascal</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.rascalmpl</string>
	<key>uuid</key>
	<string>6d5574d4-85af-4e00-9f3c-9b5fa60f53b8</string>
</dict>
</plist>